# Generated by Django 3.0.2 on 2020-03-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bought',
            fields=[
                ('date', models.DateField(auto_now_add=True, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('cost_per_item', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('date', models.DateField(auto_now_add=True, primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
            ],
        ),
    ]
