# Generated by Django 3.0.2 on 2020-03-08 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200308_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sold',
            name='date',
            field=models.DateField(default=datetime.date.today, primary_key=True, serialize=False),
        ),
    ]
