site_name: fifo_inventory
site_description: Recruitment exercise
repo_url: https://github.com/damianlewandowski/ciklum
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/damianlewandowski">damianlewandowski</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Bought: 'api/bought.md'
    - Sold: 'api/sold.md'
    - Inventory: 'api/inventory.md'
